    source of randomness in ML is a mathematical trick called pseudorandom number generator
    There is a random element to the sample of data we have collected from the domain
    data contains noise that obscure crystal-clear relationship between input and output
    use k-fold cross validation to evaluate the model on different subsets of the data
    using randomness allows an algorithem to avoid overfitting the small training set and generalize to the broader problem
    
        shuffling of training data - stochastic gradient descent
        random subset of input features - random forest
        random initial weights - neural nets
        
    two sources of randomness we must control-for: noise in the data, randomness in algortithems
    
    pseduorandomness is a sample of numbers that look close to random, but were generated from a deterministic process.
    use a seed(a parameter to start off the sequence) to generate the same sample of numbers
    python uses a pesudorandom number generator(mathematical function) called Mersenne Twister
    

## Random numbers with the Python API

In [6]:
# import the relevant libraries
from random import seed
from random import random

In [16]:
# seed random number generator
seed(1)
print(random(),random(),random())

0.13436424411240122 0.8474337369372327 0.763774618976614


In [17]:
seed(1)
print(random(),random(),random())

0.13436424411240122 0.8474337369372327 0.763774618976614


In [18]:
# random floating points
for _ in range(10):
    value = random()
    print(value)

0.2550690257394217
0.49543508709194095
0.4494910647887381
0.651592972722763
0.7887233511355132
0.0938595867742349
0.02834747652200631
0.8357651039198697
0.43276706790505337
0.762280082457942


In [19]:
range(10)

range(0, 10)

In [21]:
# random integer values

from random import randint

for _ in range(10):
    value = randint(1,10)
    print(value)

1
8
5
4
10
2
6
1
1
1


In [23]:
# random gaussian values

from random import gauss

for _ in range(10):
    value = gauss(0,1)
    print(value)

-0.08025034846938735
-0.10979532390399503
1.1183357835003105
-1.0339893191765486
1.5784400025009755
-0.31097570826361126
-1.673089745800391
-0.29340299027935385
1.1772074125986725
-0.4732313188455927


In [25]:
# random element from a list
from random import choice

sequence = [i for i in range(20)]

for _ in range(5):
    selection = choice(sequence)
    print(selection)

11
7
7
14
9


In [26]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
# random sampling without replacement

from random import sample

sequence = [i for i in range(20)]

seed(10)
sample(sequence,5)

[18, 1, 13, 15, 0]

In [38]:
# shuffle a list(performed in place)
from random import shuffle
sequence = [i for i in range(20)]
print(sequence)
shuffle(sequence)
print(sequence)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[14, 10, 0, 6, 15, 11, 3, 18, 9, 2, 12, 19, 17, 1, 13, 5, 16, 4, 8, 7]


## Random Numbers with Numpy

 - Numpy makes working with vectors and matrices of numbers very efficient
 - it has its own implementation of pseudorandom number generator

In [2]:
from numpy.random import seed
from numpy.random import rand

seed(1)
rand(3)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04])

In [8]:
rand(2,2)

array([[0.29361415, 0.28777534],
       [0.13002857, 0.01936696]])

In [9]:
rand(10)

array([0.67883553, 0.21162812, 0.26554666, 0.49157316, 0.05336255,
       0.57411761, 0.14672857, 0.58930554, 0.69975836, 0.10233443])

In [18]:
#an array of random integers
from numpy.random import randint
randint(3,size=(2,2,2))

array([[[2, 0],
        [1, 2]],

       [[0, 1],
        [1, 0]]])

In [31]:
#an array of random gaussian values
from numpy.random import randn

values = randn(1000)
values.mean()
values.std()

1.0123472857415425

In [39]:
# to scale

values = randn(1000)
scaledvalues = values*5+10

In [40]:
scaledvalues.mean()

10.272924800169962

In [41]:
scaledvalues.std()

5.139325228124799

In [42]:
#shuffle a numpy array
from numpy.random import shuffle

In [43]:
sequence = [i for i in range(10)]

In [44]:
sequence

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
shuffle(sequence)

In [46]:
sequence

[4, 8, 1, 2, 9, 3, 0, 7, 5, 6]